### GET request to example server
GET http://localhost:3000/vocab
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsa2FuZHJhbmFAZ21haWwuY29tIiwiaWF0IjoxNzc4OTAyNDkxLCJleHAiOjE3Nzg5MDI3OTF9.hC3q4C_h39dan4fYlslKsqxgHfYjHErm3JctUtJ6KfI

###